on:
  push:
    branches:
      - main

# Create an IAM user for deployment. Save the access key and secret access key associated with the user as github secrets
env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-and-deploy:
    name: Deploy Terraform resources to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Run unit tests
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      
      - name: install requirements
        run: python -m pip install -r requirements.txt
        
      - name: Run unit tests
        run: python -m pytest tests/

      # If you've got code e.g. for lambda functions contained within the src folder
      # - name: Zip up src folder
      #   run: zip -r src.zip src

      # - name: Install Terraform
      #   uses: hashicorp/setup-terraform@v2

      # - name: Terraform fmt
      #   run: terraform fmt -check
      #   continue-on-error: true

      # - name: Terraform Init
      #   run: terraform init

      # - name: Terraform Validate
      #   run: terraform validate

      # - name: Terraform Plan
      #   run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
